# Generated by Django 4.1.4 on 2022-12-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_rename_create_date_task_tracker_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tracker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
