# Generated by Django 4.1.4 on 2022-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0003_alter_task_tracker_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_tracker',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
